"""Domain models for full end-to-end analysis reports and AI synthesis."""
from typing import List, Optional, Dict
from pydantic import BaseModel, Field
from app.models.ast_models import ChangedSymbol
from app.models.graph_models import BlastRadiusReport
from app.models.risk_models import RiskReport, TestPlan


class AIExplanation(BaseModel):
    """Structured, evidence-grounded AI explanation and review checklist."""
    summary_markdown: str = Field(..., description="Developer-friendly plain English summary")
    review_checklist: List[str] = Field(
        default_factory=list,
        description="Targeted verification checklist items for code reviewers",
    )
    failure_modes: List[str] = Field(
        default_factory=list,
        description="High-probability regression scenarios if changes are incomplete",
    )
    is_generated_by_llm: bool = Field(
        default=False,
        description="True if generated by live Gemini LLM, False if generated by deterministic template",
    )


class ExecutionMetrics(BaseModel):
    """Performance telemetry for individual stages of the analysis pipeline."""
    diff_parse_ms: float = 0.0
    ast_parse_ms: float = 0.0
    graph_build_ms: float = 0.0
    traversal_ms: float = 0.0
    risk_eval_ms: float = 0.0
    ai_synthesis_ms: float = 0.0
    total_duration_ms: float = 0.0


class AnalysisSummary(BaseModel):
    """High-level summary KPIs for fast dashboard display."""
    risk_score: int
    risk_level: str
    total_files_changed: int
    total_changed_symbols: int
    breaking_candidates_count: int
    direct_impact_count: int
    transitive_impact_count: int
    total_impacted_count: int
    recommended_test_count: int
    test_reduction_ratio: float


class FullAnalysisReport(BaseModel):
    """The master end-to-end analysis artifact for a pull request or commit."""
    analysis_id: str
    repository_id: Optional[str] = None
    pr_number: Optional[int] = None
    summary: AnalysisSummary
    changed_symbols: List[ChangedSymbol] = Field(default_factory=list)
    blast_radius: BlastRadiusReport
    risk_report: RiskReport
    test_plan: TestPlan
    ai_explanation: AIExplanation
    limitations: List[str] = Field(default_factory=list)
    metrics: ExecutionMetrics
    created_at: str


class RunFullAnalysisRequest(BaseModel):
    """Request payload to execute the entire end-to-end impact analysis pipeline."""
    raw_diff: str = Field(..., description="Unified git diff text")
    files: Dict[str, str] = Field(
        ...,
        description="Head version repository files dictionary { relative_path: content }",
    )
    base_files: Optional[Dict[str, str]] = Field(
        default=None,
        description="Base version repository files (for tracking deleted symbols)",
    )
    commit_messages: Optional[List[str]] = Field(
        default=None,
        description="Recent commit messages for historical churn mining",
    )
    repository_id: Optional[str] = None
    pr_number: Optional[int] = None
