import React, { useState } from "react";
import { 
  Sparkles, 
  CheckSquare, 
  Square, 
  AlertOctagon, 
  ShieldAlert, 
  Cpu,
  Bot,
  Copy,
  Check,
  CheckCircle2
} from "lucide-react";
import { AIExplanation } from "../types/analysis";

interface AIReviewerCardProps {
  explanation: AIExplanation;
  limitations: string[];
}

export const AIReviewerCard: React.FC<AIReviewerCardProps> = ({ explanation, limitations }) => {
  const [checkedItems, setCheckedItems] = useState<Record<number, boolean>>({});
  const [copied, setCopied] = useState(false);

  const toggleCheck = (idx: number) => {
    setCheckedItems((prev) => ({ ...prev, [idx]: !prev[idx] }));
  };

  const completedCount = Object.values(checkedItems).filter(Boolean).length;
  const totalChecklist = explanation.review_checklist.length;

  const handleCopyPrComment = () => {
    const checklistMarkdown = explanation.review_checklist
      .map((item, idx) => `- [${checkedItems[idx] ? "x" : " "}] ${item}`)
      .join("\n");
    const failureMarkdown = explanation.failure_modes.length > 0
      ? "\n\n### ⚠️ Potential Failure Scenarios:\n" + explanation.failure_modes.map((f) => `- ${f}`).join("\n")
      : "";

    const text = `## 🤖 AI Change Impact Engine Review\n\n${explanation.summary_markdown}\n\n### 📋 Verification Checklist:\n${checklistMarkdown}${failureMarkdown}\n\n---\n*Generated by Google Gemini 2.5 Flash on deterministic AST blast-radius reachability.*`;
    
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="rounded-xl border border-border bg-surface p-6 shadow-xl flex flex-col gap-6">
      {/* GitHub Bot Comment Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 border-b border-border pb-4">
        <div className="flex items-center gap-3">
          <div className="relative">
            <div className="flex h-10 w-10 items-center justify-center rounded-full bg-gradient-to-br from-purple-600 via-indigo-600 to-accent text-white shadow-md">
              <Bot className="h-5 w-5" />
            </div>
            <span className="absolute -bottom-1 -right-1 flex h-4 w-4 items-center justify-center rounded-full bg-surface border border-border text-[9px] font-bold text-accent">
              ✓
            </span>
          </div>

          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-sm font-bold text-white tracking-tight">
                Antigravity Impact Bot
              </h2>
              <span className="rounded bg-purple-500/20 px-1.5 py-0.5 text-[10px] font-bold text-purple-300 border border-purple-500/30 uppercase">
                BOT
              </span>
              <span className="text-xs text-slate-500">reviewed on commit</span>
            </div>
            <p className="text-xs text-slate-400 mt-0.5">
              Strictly grounded on Tree-sitter AST syntax and NetworkX blast-radius reachability.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2 self-start sm:self-auto">
          <span
            className={`inline-flex items-center gap-1.5 rounded-lg px-2.5 py-1 text-xs font-mono font-semibold border ${
              explanation.is_generated_by_llm
                ? "bg-purple-500/15 text-purple-300 border-purple-500/30"
                : "bg-blue-500/15 text-blue-300 border-blue-500/30"
            }`}
          >
            {explanation.is_generated_by_llm ? (
              <>
                <Sparkles className="h-3 w-3 text-purple-400" />
                Gemini 2.5 Flash
              </>
            ) : (
              <>
                <Cpu className="h-3 w-3 text-blue-400" />
                Deterministic Template
              </>
            )}
          </span>

          <button
            onClick={handleCopyPrComment}
            className="flex items-center gap-1 rounded-lg border border-border bg-surface-raised px-3 py-1 text-xs font-medium text-slate-200 hover:text-white hover:border-slate-500 transition-colors"
            title="Copy formatted markdown review to paste as a GitHub PR comment"
          >
            {copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5 text-slate-400" />}
            <span>{copied ? "Copied Markdown!" : "Copy for PR"}</span>
          </button>
        </div>
      </div>

      {/* Synthesis Markdown Content */}
      <div className="rounded-xl border border-border bg-surface-raised/40 p-5">
        <div className="prose prose-invert prose-xs max-w-none text-slate-300 text-xs leading-relaxed space-y-2 whitespace-pre-wrap font-sans">
          {explanation.summary_markdown}
        </div>
      </div>

      {/* Interactive Verification Checklist */}
      <div className="flex flex-col gap-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <CheckCircle2 className="h-4 w-4 text-emerald-400" />
            <h3 className="text-xs font-bold text-white uppercase tracking-wider">
              PR Reviewer Verification Checklist
            </h3>
          </div>
          <span className="font-mono text-xs text-slate-400">
            <span className="font-bold text-emerald-400">{completedCount}</span> / {totalChecklist} Verified
          </span>
        </div>

        <div className="space-y-2">
          {explanation.review_checklist.map((item, idx) => {
            const isChecked = !!checkedItems[idx];
            return (
              <div
                key={idx}
                onClick={() => toggleCheck(idx)}
                className={`flex items-start gap-3 rounded-xl border p-3.5 cursor-pointer transition-all ${
                  isChecked
                    ? "border-emerald-500/40 bg-emerald-950/15 text-slate-200"
                    : "border-border bg-surface-raised/50 hover:bg-surface-raised hover:border-slate-600 text-slate-300"
                }`}
              >
                <div className="mt-0.5 shrink-0 text-accent">
                  {isChecked ? (
                    <CheckSquare className="h-4 w-4 text-emerald-400" />
                  ) : (
                    <Square className="h-4 w-4 text-slate-500" />
                  )}
                </div>
                <span className={`text-xs leading-relaxed ${isChecked ? "line-through text-slate-400" : ""}`}>
                  {item}
                </span>
              </div>
            );
          })}
        </div>
      </div>

      {/* Potential Failure Scenarios / Regression Risks */}
      {explanation.failure_modes.length > 0 && (
        <div className="rounded-xl border border-rose-500/30 bg-rose-950/15 p-4 flex flex-col gap-2.5">
          <div className="flex items-center gap-2 text-xs font-bold text-rose-400 uppercase tracking-wider">
            <AlertOctagon className="h-4 w-4" />
            <span>High-Probability Regression Scenarios</span>
          </div>
          <ul className="list-disc list-inside space-y-1.5 text-xs text-rose-200/90 pl-1 leading-relaxed">
            {explanation.failure_modes.map((mode, idx) => (
              <li key={idx}>{mode}</li>
            ))}
          </ul>
        </div>
      )}

      {/* Engine Limitations Disclosure */}
      {limitations.length > 0 && (
        <div className="rounded-lg bg-surface-raised/50 border border-border p-3 flex items-start gap-2.5 text-[11px] text-slate-400">
          <ShieldAlert className="h-4 w-4 text-slate-500 shrink-0 mt-0.5" />
          <div>
            <span className="font-semibold text-slate-300">Static Reachability Limitations: </span>
            <span>{limitations.join(" ")}</span>
          </div>
        </div>
      )}
    </div>
  );
};
