import { FullAnalysisReport } from "../types/analysis";

export const ECOMMERCE_BENCHMARK_REPORT: FullAnalysisReport = {
  analysis_id: "analysis_ecom_benchmark_9a2f",
  repository_id: "repo-synthetic-ecommerce",
  pr_number: 142,
  created_at: new Date().toISOString(),
  summary: {
    risk_score: 54,
    risk_level: "HIGH",
    total_files_changed: 1,
    total_changed_symbols: 1,
    breaking_candidates_count: 1,
    direct_impact_count: 1,
    transitive_impact_count: 1,
    total_impacted_count: 2,
    recommended_test_count: 2,
    test_reduction_ratio: 0.333,
  },
  changed_symbols: [
    {
      entity_id: "src/payment_service.ts::PaymentService.processTransaction",
      qualified_name: "PaymentService.processTransaction",
      entity_type: "METHOD",
      file_path: "src/payment_service.ts",
      change_nature: "SIGNATURE_MODIFIED",
      is_exported: true,
      is_breaking_candidate: true,
      diff_lines_intersected: [17],
      location: {
        start_line: 17,
        end_line: 26,
        start_col: 2,
        end_col: 3,
      },
    },
  ],
  blast_radius: {
    changed_symbol_ids: ["src/payment_service.ts::PaymentService.processTransaction"],
    direct_impact_count: 1,
    transitive_impact_count: 1,
    total_impacted_count: 2,
    max_depth_reached: 2,
    impacted_entities: [
      {
        entity_id: "src/checkout_service.ts::CheckoutService.executeCheckout",
        qualified_name: "CheckoutService.executeCheckout",
        entity_type: "METHOD",
        file_path: "src/checkout_service.ts",
        impact_type: "DIRECT",
        depth: 1,
        causal_path: [
          "src/payment_service.ts::PaymentService.processTransaction",
          "src/checkout_service.ts::CheckoutService.executeCheckout",
        ],
        confidence: 1.0,
      },
      {
        entity_id: "src/order_controller.ts::OrderController.handlePostOrder",
        qualified_name: "OrderController.handlePostOrder",
        entity_type: "METHOD",
        file_path: "src/order_controller.ts",
        impact_type: "TRANSITIVE",
        depth: 2,
        causal_path: [
          "src/payment_service.ts::PaymentService.processTransaction",
          "src/checkout_service.ts::CheckoutService.executeCheckout",
          "src/order_controller.ts::OrderController.handlePostOrder",
        ],
        confidence: 0.95,
      },
    ],
    subgraph_nodes: [
      {
        id: "src/payment_service.ts::PaymentService.processTransaction",
        label: "PaymentService.processTransaction",
        file_path: "src/payment_service.ts",
        entity_type: "METHOD",
        is_exported: true,
      },
      {
        id: "src/checkout_service.ts::CheckoutService.executeCheckout",
        label: "CheckoutService.executeCheckout",
        file_path: "src/checkout_service.ts",
        entity_type: "METHOD",
        is_exported: true,
      },
      {
        id: "src/order_controller.ts::OrderController.handlePostOrder",
        label: "OrderController.handlePostOrder",
        file_path: "src/order_controller.ts",
        entity_type: "METHOD",
        is_exported: true,
      },
    ],
    subgraph_edges: [
      {
        source_id: "src/checkout_service.ts::CheckoutService.executeCheckout",
        target_id: "src/payment_service.ts::PaymentService.processTransaction",
        relation_type: "CALLS",
        confidence: 1.0,
        is_dynamic: false,
      },
      {
        source_id: "src/order_controller.ts::OrderController.handlePostOrder",
        target_id: "src/checkout_service.ts::CheckoutService.executeCheckout",
        relation_type: "CALLS",
        confidence: 0.95,
        is_dynamic: false,
      },
    ],
    unresolved_calls: [],
  },
  risk_report: {
    risk_score: 54,
    risk_level: "HIGH",
    factors: [
      {
        factor_id: "BLAST_RADIUS_VOLUME",
        name: "Downstream Blast Radius Volume",
        weight: 25,
        raw_value: 2.0,
        contribution_points: 3,
        evidence: "2 downstream code entities potentially affected.",
      },
      {
        factor_id: "TRANSITIVE_DEPTH",
        name: "Maximum Dependency Depth",
        weight: 20,
        raw_value: 2.0,
        contribution_points: 8,
        evidence: "Changes propagate up to 2 hops away from source (OrderController -> CheckoutService -> PaymentService).",
      },
      {
        factor_id: "PUBLIC_API_BREAK",
        name: "Exported Interface Mutation",
        weight: 20,
        raw_value: 1.0,
        contribution_points: 20,
        evidence: "1 exported symbol (PaymentService.processTransaction) had method signature/parameter alterations.",
      },
      {
        factor_id: "TEST_PROXIMITY_GAP",
        name: "Test Coverage Proximity Gap",
        weight: 15,
        raw_value: 0.0,
        contribution_points: 15,
        evidence: "1 downstream consumer (OrderController) lacks dedicated unit test coverage in PR target.",
      },
      {
        factor_id: "HISTORICAL_DEFECT_CHURN",
        name: "Historical Defect Frequency",
        weight: 10,
        raw_value: 3.0,
        contribution_points: 4,
        evidence: "3 prior bugfix commits mined touching src/payment_service.ts and src/checkout_service.ts.",
      },
      {
        factor_id: "DIFF_CHURN_VOLUME",
        name: "Raw Code Churn & Surface Size",
        weight: 10,
        raw_value: 4.0,
        contribution_points: 4,
        evidence: "2 additions, 2 deletions across 1 source file.",
      },
    ],
    historical_signal: {
      is_available: true,
      commits_analyzed: 5,
      recent_bugfixes_count: 3,
      high_churn_files: ["src/payment_service.ts", "src/checkout_service.ts"],
      co_changed_files: {
        "src/payment_service.ts": ["src/checkout_service.ts"],
      },
    },
    test_plan: {
      total_repo_tests: 3,
      selected_tests_count: 2,
      test_reduction_ratio: 0.333,
      p1_count: 1,
      p2_count: 1,
      p3_count: 0,
      selected_tests: [
        {
          test_file_path: "tests/payment_service.spec.ts",
          test_name: "PaymentService Unit Suite",
          priority: "P1",
          rationale: "Directly tests modified symbol: PaymentService.processTransaction",
          target_entity_id: "src/payment_service.ts::PaymentService.processTransaction",
          path_distance: 0,
          confidence: 1.0,
        },
        {
          test_file_path: "tests/checkout_service.spec.ts",
          test_name: "CheckoutService Integration Suite",
          priority: "P2",
          rationale: "Asserts downstream consumer 1 hop away: CheckoutService.executeCheckout",
          target_entity_id: "src/checkout_service.ts::CheckoutService.executeCheckout",
          path_distance: 1,
          confidence: 0.95,
        },
      ],
    },
    limitations: [
      "Dynamic Express route bindings in order_controller.ts resolved via static AST naming heuristic.",
    ],
  },
  test_plan: {
    total_repo_tests: 3,
    selected_tests_count: 2,
    test_reduction_ratio: 0.333,
    p1_count: 1,
    p2_count: 1,
    p3_count: 0,
    selected_tests: [
      {
        test_file_path: "tests/payment_service.spec.ts",
        test_name: "PaymentService Unit Suite",
        priority: "P1",
        rationale: "Directly tests modified symbol: PaymentService.processTransaction",
        target_entity_id: "src/payment_service.ts::PaymentService.processTransaction",
        path_distance: 0,
        confidence: 1.0,
      },
      {
        test_file_path: "tests/checkout_service.spec.ts",
        test_name: "CheckoutService Integration Suite",
        priority: "P2",
        rationale: "Asserts downstream consumer 1 hop away: CheckoutService.executeCheckout",
        target_entity_id: "src/checkout_service.ts::CheckoutService.executeCheckout",
        path_distance: 1,
        confidence: 0.95,
      },
    ],
  },
  ai_explanation: {
    summary_markdown: `### Executive Impact Summary

Pull Request **#142** introduces a **signature modification** to \`PaymentService.processTransaction\` by adding a \`currency\` parameter. 

Deterministic AST reachability analysis identified **2 downstream consumers** across 2 dependency hops:
1. **Direct Impact (Hop 1)**: \`CheckoutService.executeCheckout\` directly invokes the altered method.
2. **Transitive Impact (Hop 2)**: \`OrderController.handlePostOrder\` relies on the checkout execution flow.

Because \`PaymentService.processTransaction\` is an exported public interface, unpatched callers may fail at runtime if the default argument is not honored across boundary layers.`,
    review_checklist: [
      "Verify that `CheckoutService.executeCheckout` properly forwards or defaults the `currency` parameter.",
      "Check `OrderController.handlePostOrder` input validation to confirm ISO-4217 currency strings are accepted.",
      "Execute `tests/payment_service.spec.ts` (P1) and `tests/checkout_service.spec.ts` (P2) before merging.",
      "Ensure payment gateway API mock matches the new method contract in staging.",
    ],
    failure_modes: [
      "**Runtime Parameter Mismatch**: Callers omitting `currency` could trigger gateway rejection if default argument parsing fails.",
      "**Silent Checkout Abort**: If `executeCheckout` wraps the payment call in an unlogged try/catch, payment failures may appear as cart abandonment.",
    ],
    is_generated_by_llm: true,
  },
  limitations: [
    "Dynamic Express route bindings in order_controller.ts resolved via static AST naming heuristic.",
  ],
  metrics: {
    diff_parse_ms: 0.18,
    ast_parse_ms: 2.15,
    graph_build_ms: 2.45,
    traversal_ms: 0.32,
    risk_eval_ms: 1.12,
    ai_synthesis_ms: 41.2,
    total_duration_ms: 47.42,
  },
};

export const DOC_UPDATE_REPORT: FullAnalysisReport = {
  analysis_id: "analysis_doc_update_1b8c",
  repository_id: "repo-synthetic-ecommerce",
  pr_number: 143,
  created_at: new Date().toISOString(),
  summary: {
    risk_score: 12,
    risk_level: "LOW",
    total_files_changed: 1,
    total_changed_symbols: 0,
    breaking_candidates_count: 0,
    direct_impact_count: 0,
    transitive_impact_count: 0,
    total_impacted_count: 0,
    recommended_test_count: 0,
    test_reduction_ratio: 1.0,
  },
  changed_symbols: [],
  blast_radius: {
    changed_symbol_ids: ["file:README.md"],
    direct_impact_count: 0,
    transitive_impact_count: 0,
    total_impacted_count: 0,
    max_depth_reached: 0,
    impacted_entities: [],
    subgraph_nodes: [
      {
        id: "file:README.md",
        label: "README.md",
        file_path: "README.md",
        entity_type: "FILE",
        is_exported: false,
      },
    ],
    subgraph_edges: [],
    unresolved_calls: [],
  },
  risk_report: {
    risk_score: 12,
    risk_level: "LOW",
    factors: [
      {
        factor_id: "BLAST_RADIUS_VOLUME",
        name: "Downstream Blast Radius Volume",
        weight: 25,
        raw_value: 0.0,
        contribution_points: 0,
        evidence: "0 downstream code entities affected.",
      },
      {
        factor_id: "TRANSITIVE_DEPTH",
        name: "Maximum Dependency Depth",
        weight: 20,
        raw_value: 0.0,
        contribution_points: 0,
        evidence: "No executable code dependencies touched.",
      },
      {
        factor_id: "PUBLIC_API_BREAK",
        name: "Exported Interface Mutation",
        weight: 20,
        raw_value: 0.0,
        contribution_points: 0,
        evidence: "Zero code symbols altered.",
      },
      {
        factor_id: "TEST_PROXIMITY_GAP",
        name: "Test Coverage Proximity Gap",
        weight: 15,
        raw_value: 0.0,
        contribution_points: 0,
        evidence: "Non-executable documentation change requires no test coverage.",
      },
      {
        factor_id: "HISTORICAL_DEFECT_CHURN",
        name: "Historical Defect Frequency",
        weight: 10,
        raw_value: 0.0,
        contribution_points: 2,
        evidence: "No defect hotspots associated with README.md.",
      },
      {
        factor_id: "DIFF_CHURN_VOLUME",
        name: "Raw Code Churn & Surface Size",
        weight: 10,
        raw_value: 10.0,
        contribution_points: 10,
        evidence: "10 additions in documentation.",
      },
    ],
    historical_signal: {
      is_available: false,
      commits_analyzed: 0,
      recent_bugfixes_count: 0,
      high_churn_files: [],
      co_changed_files: {},
      unavailability_reason: "Documentation file has no code bugfix history.",
    },
    test_plan: {
      total_repo_tests: 3,
      selected_tests_count: 0,
      test_reduction_ratio: 1.0,
      p1_count: 0,
      p2_count: 0,
      p3_count: 0,
      selected_tests: [],
    },
    limitations: [],
  },
  test_plan: {
    total_repo_tests: 3,
    selected_tests_count: 0,
    test_reduction_ratio: 1.0,
    p1_count: 0,
    p2_count: 0,
    p3_count: 0,
    selected_tests: [],
  },
  ai_explanation: {
    summary_markdown: `### Low-Risk Documentation Change

This change touches solely documentation (**README.md**) with 10 added lines. No executable TypeScript or Python source code was modified, resulting in **zero blast radius** and **zero regression risk**.`,
    review_checklist: [
      "Review spelling, markdown formatting, and link targets in README.md.",
      "Verify code snippets in documentation reflect current API signatures.",
    ],
    failure_modes: [],
    is_generated_by_llm: false,
  },
  limitations: [],
  metrics: {
    diff_parse_ms: 0.08,
    ast_parse_ms: 0.02,
    graph_build_ms: 0.12,
    traversal_ms: 0.01,
    risk_eval_ms: 0.22,
    ai_synthesis_ms: 0.15,
    total_duration_ms: 0.6,
  },
};
